# Generated by Django 5.0.6 on 2025-08-18 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinictime',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='clinictime',
            name='open_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
