# Generated by Django 5.0.6 on 2025-09-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_adminuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuserprofile',
            name='designation',
        ),
    ]
