# Generated by Django 5.0.6 on 2025-09-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_datetime', models.DateTimeField(auto_now_add=True)),
                ('healthcare_number', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=10)),
                ('dob', models.DateField()),
                ('p_age', models.IntegerField()),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20, null=True)),
                ('emergency_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_registration', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('insurance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='patient/patientImg')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.DateField()),
                ('apptime', models.TimeField()),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0')),
                ('is_active', models.CharField(choices=[('0', 'Active'), ('1', 'Cancel'), ('2', 'Completed'), ('3', 'Pending')], default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appDate', models.DateField()),
                ('appTime', models.TimeField()),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_appointment', to='patients.apointment')),
            ],
        ),
    ]
