# Generated by Django 5.0.6 on 2025-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='patient/patientImg'),
        ),
    ]
