# Generated by Django 5.0.6 on 2025-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='is_active',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Cancel'), ('2', 'Completed'), ('3', 'Pending')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0', max_length=100),
        ),
    ]
