# Generated by Django 5.0.6 on 2025-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
