# Generated by Django 5.0.6 on 2025-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='p_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
