# Generated by Django 5.0.6 on 2025-08-25 09:56

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_p_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.DateField()),
                ('apptime', models.TimeField()),
                ('status', django_mysql.models.EnumField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial')], default='0')),
                ('is_active', django_mysql.models.EnumField(choices=[('0', 'Active'), ('1', 'Cancel'), ('2', 'Completed'), ('3', 'Pending')], default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='patients.patientprofile')),
            ],
        ),
    ]
