# Generated by Django 5.0.6 on 2025-09-01 11:05

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientprofile_doctor_apointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appDate', models.DateField()),
                ('appTime', models.TimeField()),
                ('status', django_mysql.models.EnumField(choices=[('0', '0'), ('Pending', 'Pending'), ('1', '1'), ('Paid', 'Paid'), ('2', '2'), ('Failed', 'Failed')], default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
