# Generated by Django 5.0.6 on 2025-09-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.apointment'),
        ),
    ]
