# Generated by Django 5.0.6 on 2025-09-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_paymenthistory_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='patient',
            new_name='appointment',
        ),
    ]
