# Generated by Django 5.0.6 on 2025-09-01 11:38

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_rename_patient_paymenthistory_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='status',
            field=django_mysql.models.EnumField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial'), ('3', 'Failed')], default='0'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=django_mysql.models.EnumField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial'), ('3', 'Failed')], default='0'),
        ),
    ]
