# Generated by Django 5.0.6 on 2025-09-01 12:33

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_apointment_status_alter_paymenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='status',
            field=django_mysql.models.EnumField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=django_mysql.models.EnumField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Partial Paid'), ('3', 'Failed')], default='0'),
        ),
    ]
