# Generated by Django 5.0.6 on 2025-09-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_apointment_status_alter_paymenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_payment', to='patients.apointment'),
        ),
    ]
