# Generated by Django 5.0.6 on 2025-09-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_paymenthistory_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appoint', to='patients.apointment'),
        ),
    ]
